# Generated by Django 4.2.6 on 2024-02-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Contacts Subscribed / Contactos Subscritos',
                'verbose_name_plural': 'Contacts Subscribed / Contactos Subscritos',
            },
        ),
        migrations.CreateModel(
            name='Contacting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name / Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email / Email')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone Number / Número de Teléfono')),
                ('msg', models.TextField(verbose_name='Message / Mensaje')),
            ],
            options={
                'verbose_name': 'Contacts / Contactos',
                'verbose_name_plural': 'Contacts / Contactos',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name / Nombre')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Managers / Gestores',
                'verbose_name_plural': 'Managers / Gestores',
            },
        ),
    ]
