# Generated by Django 5.0 on 2024-01-02 15:17

import Main.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('image', models.ImageField(upload_to=Main.models.about_us)),
                ('read_more', models.TextField(verbose_name='Learn More / Saber más')),
            ],
            options={
                'verbose_name': 'About Us / Acerca de Nosotros',
                'verbose_name_plural': 'About Us / Acerca de Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('sub_title', models.TextField(verbose_name='Subtitle / Subtítulo')),
                ('image', models.ImageField(upload_to=Main.models.carrousel_img, verbose_name='Image / Imágen')),
                ('button_link', models.CharField(max_length=500, verbose_name='Button Link / Enlace del Botón')),
                ('title_1', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('sub_title_1', models.TextField(verbose_name='Subtitle / Subtítulo')),
                ('image_1', models.ImageField(upload_to=Main.models.carrousel_img, verbose_name='Image / Imágen')),
                ('button_link_1', models.CharField(max_length=500, verbose_name='Button Link / Enlace del Botón')),
                ('title_2', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('sub_title_2', models.TextField(verbose_name='Subtitle / Subtítulo')),
                ('image_2', models.ImageField(upload_to=Main.models.carrousel_img, verbose_name='Image / Imágen')),
                ('button_link_2', models.CharField(max_length=500, verbose_name='Button Link / Enlace del Botón')),
            ],
            options={
                'verbose_name': 'Carrousel / Carrusel',
                'verbose_name_plural': 'Carrousel / Carrusel',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title/Título')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone / Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', models.CharField(max_length=200, verbose_name='Location / Ubicación')),
            ],
            options={
                'verbose_name': 'Header / Encabezado',
                'verbose_name_plural': 'Header / Encabezado',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('sub_title', models.TextField(verbose_name='Subtitle / Subtítulo')),
            ],
            options={
                'verbose_name': 'Service / Servicio',
                'verbose_name_plural': 'Services / Servicios',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', models.CharField(max_length=30, verbose_name='Main Color / Color Principal')),
                ('button_colors', models.CharField(max_length=30, verbose_name='Button Colors / Colores de los Botones')),
            ],
            options={
                'verbose_name': 'Theme / Tema',
                'verbose_name_plural': 'Theme / Tema',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('image', models.ImageField(upload_to=Main.models.track_img)),
                ('number_text', models.CharField(max_length=250)),
                ('btn', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Track Shiping / Encontrar Carga',
                'verbose_name_plural': 'Track Shiping / Encontrar Carga',
            },
        ),
        migrations.CreateModel(
            name='Services_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to=Main.models.si_img)),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.service')),
            ],
        ),
    ]
