# Generated by Django 5.0 on 2023-12-30 15:21

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=Main.models.about_us)),
            ],
        ),
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('sub_title', models.TextField()),
                ('image', models.ImageField(upload_to=Main.models.carrousel_img)),
                ('button_link', models.CharField(max_length=500)),
                ('title_1', models.CharField(max_length=500)),
                ('sub_title_1', models.TextField()),
                ('image_1', models.ImageField(upload_to=Main.models.carrousel_img)),
                ('button_link_1', models.CharField(max_length=500)),
                ('title_2', models.CharField(max_length=500)),
                ('sub_title_2', models.TextField()),
                ('image_2', models.ImageField(upload_to=Main.models.carrousel_img)),
                ('button_link_2', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('info_details', models.TextField()),
                ('facebook', models.CharField(max_length=500)),
                ('twitter', models.CharField(max_length=500)),
                ('i_n', models.CharField(max_length=500)),
                ('instagram', models.CharField(max_length=500)),
                ('copyright', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Our_clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Our_clients_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Main.models.user_img)),
                ('name', models.CharField(max_length=500)),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('sub_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to=Main.models.si_img)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', models.CharField(max_length=30)),
                ('button_colors', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=Main.models.track_img)),
            ],
        ),
    ]
