# Generated by Django 4.2.6 on 2024-02-07 17:32

import Main.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('image', models.ImageField(upload_to=Main.models.about_us, verbose_name='Image / Imagen')),
                ('read_more', models.CharField(max_length=50, verbose_name='Learn More / Saber más')),
                ('detail', models.TextField(verbose_name='Datails / Detalles')),
            ],
            options={
                'verbose_name': 'About Us / Acerca de Nosotros',
                'verbose_name_plural': 'About Us / Acerca de Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('sub_title', models.TextField(verbose_name='Subtitle / Subtítulo')),
                ('image', models.ImageField(upload_to=Main.models.carrousel_img, verbose_name='Image / Imágen')),
                ('button_link', models.CharField(max_length=500, verbose_name='Button Link / Enlace del Botón')),
                ('title_1', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('sub_title_1', models.TextField(verbose_name='Subtitle / Subtítulo')),
                ('image_1', models.ImageField(upload_to=Main.models.carrousel_img, verbose_name='Image / Imágen')),
                ('button_link_1', models.CharField(max_length=500, verbose_name='Button Link / Enlace del Botón')),
                ('title_2', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('sub_title_2', models.TextField(verbose_name='Subtitle / Subtítulo')),
                ('image_2', models.ImageField(upload_to=Main.models.carrousel_img, verbose_name='Image / Imágen')),
                ('button_link_2', models.CharField(max_length=500, verbose_name='Button Link / Enlace del Botón')),
            ],
            options={
                'verbose_name': 'Carrousel / Carrusel',
                'verbose_name_plural': 'Carrousel / Carrusel',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_link', models.CharField(max_length=500, verbose_name='Map Link / Link del Mapa')),
                ('name', models.CharField(max_length=500, verbose_name='Name / Nombre')),
                ('email', models.CharField(max_length=500, verbose_name='Email / Email')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone Number / Número de Teléfono')),
                ('message', models.CharField(max_length=500, verbose_name='Message / Mensaje')),
                ('send_text', models.CharField(max_length=500, verbose_name='Send Text / Texto de Enviar')),
            ],
            options={
                'verbose_name': 'Contact Us / Contactenos',
                'verbose_name_plural': 'Contact Us / Contactenos',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Address / Dirección')),
                ('location', models.CharField(max_length=500, verbose_name='Location / Ubicación')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone / Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email / Email')),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('linked_in', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('info', models.TextField(verbose_name='Info / Info')),
            ],
            options={
                'verbose_name': 'Footer / Pie de Página',
                'verbose_name_plural': 'Footer / Pie de Página',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title/Título')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone / Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', models.CharField(max_length=200, verbose_name='Location / Ubicación')),
            ],
            options={
                'verbose_name': 'Header / Encabezado',
                'verbose_name_plural': 'Header / Encabezado',
            },
        ),
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title / Título')),
            ],
            options={
                'verbose_name': 'Reviews / Opiniones',
                'verbose_name_plural': 'Reviews / Opiniones',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('sub_title', models.TextField(verbose_name='Subtitle / Subtítulo')),
            ],
            options={
                'verbose_name': 'Service / Servicio',
                'verbose_name_plural': 'Services / Servicios',
            },
        ),
        migrations.CreateModel(
            name='Shiping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Text / Texto')),
            ],
            options={
                'verbose_name': 'Find shiping / Buscar envío',
                'verbose_name_plural': 'Find shiping / Buscar envío',
            },
        ),
        migrations.CreateModel(
            name='Suscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500, verbose_name='Email / Email')),
                ('texto_submit', models.CharField(max_length=500, verbose_name='Text Suscribe / Text de Suscripcion')),
                ('copyright', models.CharField(max_length=500, verbose_name='Copyright')),
            ],
            options={
                'verbose_name': 'Subscribe / Subscripción',
                'verbose_name_plural': 'Subscribe / Subscripción',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', models.CharField(max_length=210, verbose_name='Main Color / Color Principal')),
                ('button_colors', models.CharField(max_length=210, verbose_name='Button Colors / Colores de los Botones')),
            ],
            options={
                'verbose_name': 'Theme / Tema',
                'verbose_name_plural': 'Theme / Tema',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title / Título')),
                ('detail', models.TextField(verbose_name='Datails / Detalles')),
                ('image', models.ImageField(upload_to=Main.models.track_img, verbose_name='Image / Imagen')),
                ('number_text', models.CharField(max_length=50, verbose_name='Traking Number Text / Texto de Encontrar Carga')),
                ('btn', models.CharField(max_length=250, verbose_name='Track Button / Boton de Encontrar')),
            ],
            options={
                'verbose_name': 'Track Shiping / Encontrar Carga',
                'verbose_name_plural': 'Track Shiping / Encontrar Carga',
            },
        ),
        migrations.CreateModel(
            name='Services_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name / Nombre')),
                ('detail', models.TextField(verbose_name='Details / Detalles')),
                ('image', models.ImageField(upload_to=Main.models.si_img, verbose_name='Image / Imagen')),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Main.service')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Main.models.user_img, verbose_name='Image / Imagen')),
                ('name', models.CharField(max_length=500, verbose_name='Name / Nombre')),
                ('review', models.TextField(verbose_name='Review / Opinion')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Main.reviewsection')),
            ],
            options={
                'verbose_name': 'Review / Opinion',
                'verbose_name_plural': 'Reviews / Opiniones',
            },
        ),
    ]
