# Generated by Django 5.0 on 2023-12-31 19:40

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Header / Encabezado', 'verbose_name_plural': 'Header / Encabezado'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Theme / Tema', 'verbose_name_plural': 'Theme / Tema'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title/Título'),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='button_link',
            field=models.CharField(max_length=500, verbose_name='Button Link / Enlace del Botón'),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='button_link_1',
            field=models.CharField(max_length=500, verbose_name='Button Link / Enlace del Botón'),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='button_link_2',
            field=models.CharField(max_length=500, verbose_name='Button Link / Enlace del Botón'),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='image',
            field=models.ImageField(upload_to=Main.models.carrousel_img, verbose_name='Image / Imágen'),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='image_1',
            field=models.ImageField(upload_to=Main.models.carrousel_img, verbose_name='Image / Imágen'),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='image_2',
            field=models.ImageField(upload_to=Main.models.carrousel_img, verbose_name='Image / Imágen'),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='sub_title',
            field=models.TextField(verbose_name='Subtitle / Subtítulo'),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='sub_title_1',
            field=models.TextField(verbose_name='Subtitle / Subtítulo'),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='sub_title_2',
            field=models.TextField(verbose_name='Subtitle / Subtítulo'),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title / Título'),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='title_1',
            field=models.CharField(max_length=500, verbose_name='Title / Título'),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='title_2',
            field=models.CharField(max_length=500, verbose_name='Title / Título'),
        ),
        migrations.AlterField(
            model_name='header',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='header',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Location / Ubicación'),
        ),
        migrations.AlterField(
            model_name='header',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Phone / Teléfono'),
        ),
        migrations.AlterField(
            model_name='header',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title/Título'),
        ),
        migrations.AlterField(
            model_name='our_clients',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title/Título'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_title',
            field=models.TextField(verbose_name='Subtitle/Subtítulo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title/Título'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='button_colors',
            field=models.CharField(max_length=30, verbose_name='Button Colors / Colores de los Botones'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='main_color',
            field=models.CharField(max_length=30, verbose_name='Main Color / Color Principal'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title/Título'),
        ),
    ]
