# Generated by Django 5.0 on 2024-02-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscribe',
            name='copyright',
        ),
        migrations.AddField(
            model_name='footer',
            name='copyright',
            field=models.CharField(default='copyright', max_length=500, verbose_name='Copyright'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='read_more',
            field=models.TextField(verbose_name='Learn More / Saber más'),
        ),
    ]
