# Generated by Django 5.0 on 2023-12-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_header_options_alter_theme_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrousel',
            options={'verbose_name': 'Carrousel / Carrusel', 'verbose_name_plural': 'Carrousel / Carrusel'},
        ),
    ]
