# Generated by Django 5.0 on 2024-02-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_suscribe_copyright_footer_copyright_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='read_more',
            field=models.CharField(max_length=50, verbose_name='Learn More / Saber más'),
        ),
    ]
